import { Resource as $Resource } from "../template/Resource.js";
import { ResourceOptions as $ResourceOptions } from "../template.js";
/**
 * The AWS::ElastiCache::GlobalReplicationGroup resource creates an Amazon ElastiCache Global Replication Group.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-globalreplicationgroup.html}
 */
export type ElastiCacheGlobalReplicationGroupProperties = {
  /**
   * AutomaticFailoverEnabled
   */
  AutomaticFailoverEnabled?: boolean;
  /**
   * The cache node type of the Global Datastore
   */
  CacheNodeType?: string;
  /**
   * Cache parameter group name to use for the new engine version. This parameter cannot be modified independently.
   */
  CacheParameterGroupName?: string;
  /**
   * The engine version of the Global Datastore.
   */
  EngineVersion?: string;
  /**
   * Indicates the number of node groups in the Global Datastore.
   */
  GlobalNodeGroupCount?: number;
  /**
   * The optional description of the Global Datastore
   */
  GlobalReplicationGroupDescription?: string;
  /**
   * The suffix name of a Global Datastore. Amazon ElastiCache automatically applies a prefix to the Global Datastore ID when it is created. Each AWS Region has its own prefix.
   */
  GlobalReplicationGroupIdSuffix?: string;
  /**
   * The replication groups that comprise the Global Datastore.
   * @minLength `1`
   */
  Members: GlobalReplicationGroupMember[];
  /**
   * Describes the replication group IDs, the AWS regions where they are stored and the shard configuration for each that comprise the Global Datastore
   */
  RegionalConfigurations?: RegionalConfiguration[];
};
/**
 * Attribute type definition for `AWS::ElastiCache::GlobalReplicationGroup`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-globalreplicationgroup.html#aws-resource-elasticache-globalreplicationgroup-return-values}
 */
export type ElastiCacheGlobalReplicationGroupAttributes = {
  /**
   * The name of the Global Datastore, it is generated by ElastiCache adding a prefix to GlobalReplicationGroupIdSuffix.
   */
  GlobalReplicationGroupId: string;
  /**
   * The status of the Global Datastore
   */
  Status: string;
};
/**
 * Type definition for `AWS::ElastiCache::GlobalReplicationGroup.GlobalReplicationGroupMember`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-globalreplicationgroup-globalreplicationgroupmember.html}
 */
export type GlobalReplicationGroupMember = {
  /**
   * Regionally unique identifier for the member i.e. ReplicationGroupId.
   */
  ReplicationGroupId?: string;
  /**
   * The AWS region of the Global Datastore member.
   */
  ReplicationGroupRegion?: string;
  /**
   * Indicates the role of the member, primary or secondary.
   */
  Role?: "PRIMARY" | "SECONDARY";
};
/**
 * Type definition for `AWS::ElastiCache::GlobalReplicationGroup.RegionalConfiguration`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-globalreplicationgroup-regionalconfiguration.html}
 */
export type RegionalConfiguration = {
  /**
   * The replication group id of the Global Datastore member.
   */
  ReplicationGroupId?: string;
  /**
   * The AWS region of the Global Datastore member.
   */
  ReplicationGroupRegion?: string;
  /**
   * A list of PreferredAvailabilityZones objects that specifies the configuration of a node group in the resharded cluster.
   */
  ReshardingConfigurations?: ReshardingConfiguration[];
};
/**
 * Type definition for `AWS::ElastiCache::GlobalReplicationGroup.ReshardingConfiguration`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-globalreplicationgroup-reshardingconfiguration.html}
 */
export type ReshardingConfiguration = {
  /**
   * Unique identifier for the Node Group. This is either auto-generated by ElastiCache (4-digit id) or a user supplied id.
   */
  NodeGroupId?: string;
  /**
   * A list of preferred availability zones for the nodes of new node groups.
   */
  PreferredAvailabilityZones?: string[];
};
/**
 * The AWS::ElastiCache::GlobalReplicationGroup resource creates an Amazon ElastiCache Global Replication Group.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-globalreplicationgroup.html}
 */
export class ElastiCacheGlobalReplicationGroup extends $Resource<
  "AWS::ElastiCache::GlobalReplicationGroup",
  ElastiCacheGlobalReplicationGroupProperties,
  ElastiCacheGlobalReplicationGroupAttributes
> {
  public static readonly Type = "AWS::ElastiCache::GlobalReplicationGroup";
  public static readonly AttributeNames = [
    "GlobalReplicationGroupId" as const,
    "Status" as const,
  ];
  constructor(
    logicalId: string,
    properties: ElastiCacheGlobalReplicationGroupProperties,
    options?: $ResourceOptions,
  ) {
    super(
      logicalId,
      ElastiCacheGlobalReplicationGroup.Type,
      properties,
      ElastiCacheGlobalReplicationGroup.AttributeNames,
      options,
    );
  }
}
