import { Resource as $Resource } from "../template/Resource.js";
import { ResourceOptions as $ResourceOptions } from "../template.js";
/**
 * Schema for AWS::EMR::Step
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-step.html}
 */
export type EMRStepProperties = {
  /**
   * This specifies what action to take when the cluster step fails. Possible values are CANCEL_AND_WAIT and CONTINUE.
   */
  ActionOnFailure: string;
  /**
   * The HadoopJarStepConfig property type specifies a job flow step consisting of a JAR file whose main function will be executed. The main function submits a job for the cluster to execute as a step on the master node, and then waits for the job to finish or fail before executing subsequent steps.
   */
  HadoopJarStep: HadoopJarStepConfig;
  /**
   * A string that uniquely identifies the cluster (job flow).
   */
  JobFlowId: string;
  /**
   * The name of the cluster step.
   */
  Name: string;
};
/**
 * Attribute type definition for `AWS::EMR::Step`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-step.html#aws-resource-emr-step-return-values}
 */
export type EMRStepAttributes = {
  /**
   * ID generated by service
   */
  Id: string;
};
/**
 * Type definition for `AWS::EMR::Step.HadoopJarStepConfig`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emr-step-hadoopjarstepconfig.html}
 */
export type HadoopJarStepConfig = {
  Args?: string[];
  Jar: string;
  MainClass?: string;
  StepProperties?: KeyValue[];
};
/**
 * Type definition for `AWS::EMR::Step.KeyValue`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emr-step-keyvalue.html}
 */
export type KeyValue = {
  Key?: string;
  Value?: string;
};
/**
 * Schema for AWS::EMR::Step
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-step.html}
 */
export class EMRStep extends $Resource<
  "AWS::EMR::Step",
  EMRStepProperties,
  EMRStepAttributes
> {
  public static readonly Type = "AWS::EMR::Step";
  public static readonly AttributeNames = ["Id" as const];
  constructor(
    logicalId: string,
    properties: EMRStepProperties,
    options?: $ResourceOptions,
  ) {
    super(logicalId, EMRStep.Type, properties, EMRStep.AttributeNames, options);
  }
}
