import { Resource as $Resource } from "../template/Resource.js";
import { ResourceOptions as $ResourceOptions } from "../template.js";
/**
 * Resource type definition for `AWS::Lambda::LayerVersionPermission`.
 * Schema for Lambda LayerVersionPermission
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-layerversionpermission.html}
 */
export type LambdaLayerVersionPermissionProperties = {
  /**
   * The API action that grants access to the layer.
   */
  Action: string;
  /**
   * The name or Amazon Resource Name (ARN) of the layer.
   */
  LayerVersionArn: string;
  /**
   * With the principal set to *, grant permission to all accounts in the specified organization.
   */
  OrganizationId?: string;
  /**
   * An account ID, or * to grant layer usage permission to all accounts in an organization, or all AWS accounts (if organizationId is not specified).
   */
  Principal: string;
};
/**
 * Attribute type definition for `AWS::Lambda::LayerVersionPermission`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-layerversionpermission.html#aws-resource-lambda-layerversionpermission-return-values}
 */
export type LambdaLayerVersionPermissionAttributes = {
  /**
   * ID generated by service
   */
  Id: string;
};
/**
 * Resource type definition for `AWS::Lambda::LayerVersionPermission`.
 * Schema for Lambda LayerVersionPermission
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-layerversionpermission.html}
 */
export class LambdaLayerVersionPermission extends $Resource<
  "AWS::Lambda::LayerVersionPermission",
  LambdaLayerVersionPermissionProperties,
  LambdaLayerVersionPermissionAttributes
> {
  public static readonly Type = "AWS::Lambda::LayerVersionPermission";
  public static readonly AttributeNames = ["Id" as const];
  constructor(
    logicalId: string,
    properties: LambdaLayerVersionPermissionProperties,
    options?: $ResourceOptions,
  ) {
    super(
      logicalId,
      LambdaLayerVersionPermission.Type,
      properties,
      LambdaLayerVersionPermission.AttributeNames,
      options,
    );
  }
}
