import { Resource as $Resource } from "../template/Resource.js";
import { ResourceOptions as $ResourceOptions } from "../template.js";
/**
 * Resource Type definition for AWS::EC2::VPCEndpointConnectionNotification
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointconnectionnotification.html}
 */
export type EC2VPCEndpointConnectionNotificationProperties = {
  /**
   * The endpoint events for which to receive notifications.
   */
  ConnectionEvents: string[];
  /**
   * The ARN of the SNS topic for the notifications.
   */
  ConnectionNotificationArn: string;
  /**
   * The ID of the endpoint service.
   */
  ServiceId?: string;
  /**
   * The ID of the endpoint.
   */
  VPCEndpointId?: string;
};
/**
 * Attribute type definition for `AWS::EC2::VPCEndpointConnectionNotification`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointconnectionnotification.html#aws-resource-ec2-vpcendpointconnectionnotification-return-values}
 */
export type EC2VPCEndpointConnectionNotificationAttributes = {
  /**
   * VPC Endpoint Connection ID generated by service
   */
  VPCEndpointConnectionNotificationId: string;
};
/**
 * Resource Type definition for AWS::EC2::VPCEndpointConnectionNotification
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointconnectionnotification.html}
 */
export class EC2VPCEndpointConnectionNotification extends $Resource<
  "AWS::EC2::VPCEndpointConnectionNotification",
  EC2VPCEndpointConnectionNotificationProperties,
  EC2VPCEndpointConnectionNotificationAttributes
> {
  public static readonly Type = "AWS::EC2::VPCEndpointConnectionNotification";
  public static readonly AttributeNames = [
    "VPCEndpointConnectionNotificationId" as const,
  ];
  constructor(
    logicalId: string,
    properties: EC2VPCEndpointConnectionNotificationProperties,
    options?: $ResourceOptions,
  ) {
    super(
      logicalId,
      EC2VPCEndpointConnectionNotification.Type,
      properties,
      EC2VPCEndpointConnectionNotification.AttributeNames,
      options,
    );
  }
}
