import { Resource as $Resource } from "../template/Resource.js";
import { ResourceOptions as $ResourceOptions } from "../template.js";
/**
 * Resource Type definition for AWS::Lightsail::Database
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-database.html}
 */
export type LightsailDatabaseProperties = {
  /**
   * The Availability Zone in which to create your new database. Use the us-east-2a case-sensitive format.
   * @minLength `1`
   * @maxLength `255`
   */
  AvailabilityZone?: string;
  /**
   * When true, enables automated backup retention for your database. Updates are applied during the next maintenance window because this can result in an outage.
   */
  BackupRetention?: boolean;
  /**
   * Indicates the certificate that needs to be associated with the database.
   */
  CaCertificateIdentifier?: string;
  /**
   * The name of the database to create when the Lightsail database resource is created. For MySQL, if this parameter isn't specified, no database is created in the database resource. For PostgreSQL, if this parameter isn't specified, a database named postgres is created in the database resource.
   * @minLength `1`
   * @maxLength `255`
   */
  MasterDatabaseName: string;
  /**
   * The password for the master user. The password can include any printable ASCII character except "/", """, or "@". It cannot contain spaces.
   * @minLength `1`
   * @maxLength `63`
   */
  MasterUserPassword?: string;
  /**
   * The name for the master user.
   * @minLength `1`
   * @maxLength `63`
   */
  MasterUsername: string;
  /**
   * The daily time range during which automated backups are created for your new database if automated backups are enabled.
   */
  PreferredBackupWindow?: string;
  /**
   * The weekly time range during which system maintenance can occur on your new database.
   */
  PreferredMaintenanceWindow?: string;
  /**
   * Specifies the accessibility options for your new database. A value of true specifies a database that is available to resources outside of your Lightsail account. A value of false specifies a database that is available only to your Lightsail resources in the same region as your database.
   */
  PubliclyAccessible?: boolean;
  /**
   * The blueprint ID for your new database. A blueprint describes the major engine version of a database.
   * @minLength `1`
   * @maxLength `255`
   */
  RelationalDatabaseBlueprintId: string;
  /**
   * The bundle ID for your new database. A bundle describes the performance specifications for your database.
   * @minLength `1`
   * @maxLength `255`
   */
  RelationalDatabaseBundleId: string;
  /**
   * The name to use for your new Lightsail database resource.
   * @minLength `2`
   * @maxLength `255`
   * @pattern `\w[\w\-]*\w`
   */
  RelationalDatabaseName: string;
  /**
   * Update one or more parameters of the relational database.
   */
  RelationalDatabaseParameters?: RelationalDatabaseParameter[];
  /**
   * When true, the master user password is changed to a new strong password generated by Lightsail. Use the get relational database master user password operation to get the new password.
   */
  RotateMasterUserPassword?: boolean;
  /**
   * An array of key-value pairs to apply to this resource.
   */
  Tags?: Tag[];
};
/**
 * Attribute type definition for `AWS::Lightsail::Database`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-database.html#aws-resource-lightsail-database-return-values}
 */
export type LightsailDatabaseAttributes = {
  DatabaseArn: string;
};
/**
 * Type definition for `AWS::Lightsail::Database.RelationalDatabaseParameter`.
 * Describes the parameters of the database.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lightsail-database-relationaldatabaseparameter.html}
 */
export type RelationalDatabaseParameter = {
  /**
   * Specifies the valid range of values for the parameter.
   */
  AllowedValues?: string;
  /**
   * Indicates when parameter updates are applied. Can be immediate or pending-reboot.
   */
  ApplyMethod?: string;
  /**
   * Specifies the engine-specific parameter type.
   */
  ApplyType?: string;
  /**
   * Specifies the valid data type for the parameter.
   */
  DataType?: string;
  /**
   * Provides a description of the parameter.
   */
  Description?: string;
  /**
   * A Boolean value indicating whether the parameter can be modified.
   */
  IsModifiable?: boolean;
  /**
   * Specifies the name of the parameter.
   */
  ParameterName?: string;
  /**
   * Specifies the value of the parameter.
   */
  ParameterValue?: string;
};
/**
 * Type definition for `AWS::Lightsail::Database.Tag`.
 * A key-value pair to associate with a resource.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lightsail-database-tag.html}
 */
export type Tag = {
  /**
   * The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   * @minLength `1`
   * @maxLength `128`
   */
  Key: string;
  /**
   * The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
   * @maxLength `256`
   */
  Value?: string;
};
/**
 * Resource Type definition for AWS::Lightsail::Database
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-database.html}
 */
export class LightsailDatabase extends $Resource<
  "AWS::Lightsail::Database",
  LightsailDatabaseProperties,
  LightsailDatabaseAttributes
> {
  public static readonly Type = "AWS::Lightsail::Database";
  public static readonly AttributeNames = ["DatabaseArn" as const];
  constructor(
    logicalId: string,
    properties: LightsailDatabaseProperties,
    options?: $ResourceOptions,
  ) {
    super(
      logicalId,
      LightsailDatabase.Type,
      properties,
      LightsailDatabase.AttributeNames,
      options,
    );
  }
}
